cc_library(
    name="stringutil",
    srcs="stringutil.cpp",
)

cc_test(
    name = 'stringutil_test',
    srcs = 'stringutil_test.cpp',
    deps=[
        ":stringutil",
        "//cpputil/gtest:gtest_v1"
    ]
)
